# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackunderflow', '0002_auto_20160517_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='creator',
        ),
    ]
