# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.6 on 2016-05-18 19:51
=======
<<<<<<< HEAD
# Generated by Django 1.9.6 on 2016-05-18 15:16
=======
# Generated by Django 1.9.6 on 2016-05-18 14:43
>>>>>>> 53ceb3724c62bd0dbf82fb90a1bd26e8242b57df
>>>>>>> 8d45e01dbf19797f1256c05919e1dccfc4794762
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackunderflow', '0006_auto_20160517_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='keywords',
<<<<<<< HEAD
            field=models.CharField(blank=True, max_length=250),
=======
<<<<<<< HEAD
            field=models.CharField(blank=True, max_length=250),
=======
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
>>>>>>> 53ceb3724c62bd0dbf82fb90a1bd26e8242b57df
>>>>>>> 8d45e01dbf19797f1256c05919e1dccfc4794762
        ),
    ]
