# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackunderflow', '0008_auto_20160519_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='keywords',
            field=models.ManyToManyField(default='', null=True, to='stackunderflow.Keyword'),
        ),
    ]
